import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Generated by hand based on the Firebase configuration files bundled with the project.
/// If you reconfigure Firebase, regenerate this file with `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for platform: ${defaultTargetPlatform.name}',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4CQjyPhpGACwG4zTxVJlM3vZcpSvvDFA',
    appId: '1:66150861995:android:73b30f3f92bbe17e1e3bee',
    messagingSenderId: '66150861995',
    projectId: 'vendor-connect-3812e',
    storageBucket: 'vendor-connect-3812e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05CT1qS0uh9oKE5OGBPO2T8gU0S5Uues',
    appId: '1:66150861995:ios:057c57cbf4110da81e3bee',
    messagingSenderId: '66150861995',
    projectId: 'vendor-connect-3812e',
    storageBucket: 'vendor-connect-3812e.firebasestorage.app',
    iosBundleId: 'com.vendorconnectapp.mobile',
  );
}
